version: "3.8"

services:
# Routers
  routeur_1:
    image: mongo:6
    container_name: routeur_1
    ports:
      - "27041:27017"
    command: ["mongos", "--configdb", "configReplSet/config_server_1:27017,config_server_2:27017,config_server_3:27017", "--bind_ip_all"]
    depends_on:
      - config_server_1
      - config_server_2
      - config_server_3
    networks:
      - mongoCluster

  routeur_2:
    image: mongo:6
    container_name: routeur_2
    ports:
      - "27040:27017"
    command: ["mongos", "--configdb", "configReplSet/config_server_1:27017,config_server_2:27017,config_server_3:27017", "--bind_ip_all"]
    depends_on:
      - config_server_1
      - config_server_2
      - config_server_3
    networks:
      - mongoCluster
  # Config server
  config_server_1:
    image: mongo:6
    container_name: config_server_1
    hostname: config_server_1
    ports:
      - "27031:27017"
    command: ["mongod", "--replSet", "configReplSet", "--configsvr", "--bind_ip_all", "--port", "27017"]
    volumes:
      - ./data/config_server_1:/data/db
    networks:
      - mongoCluster

  config_server_2:
    image: mongo:6
    container_name: config_server_2
    hostname: config_server_2
    ports:
      - "27032:27017"
    command: ["mongod", "--replSet", "configReplSet", "--configsvr", "--bind_ip_all", "--port", "27017"]
    volumes:
      - ./data/config_server_2:/data/db
    networks:
      - mongoCluster

  config_server_3:
    image: mongo:6
    container_name: config_server_3
    hostname: config_server_3
    ports:
      - "27033:27017"
    command: ["mongod", "--replSet", "configReplSet", "--configsvr", "--bind_ip_all", "--port", "27017"]
    volumes:
      - ./data/config_server_3:/data/db
    networks:
      - mongoCluster
  # serveur a
  principal_a:
    image: mongo:6
    container_name: principal_a
    hostname: principal_a
    ports:
      - "27017:27017"
    command: ["mongod", "--replSet", "replicaSet_a", "--shardsvr", "--bind_ip_all", "--port", "27017"]
    volumes:
      - ./data/principal_a:/data/db
    networks:
      - mongoCluster
      
  secondaire_a_1:
    image: mongo:6
    container_name: secondaire_a_1
    hostname: secondaire_a_1
    ports:
      - "27018:27017"
    command: ["mongod", "--replSet", "replicaSet_a", "--shardsvr", "--bind_ip_all", "--port", "27017"]
    volumes:
      - ./data/secondaire_a_1:/data/db
    networks:
      - mongoCluster
  
  secondaire_a_2:
    image: mongo:6
    container_name: secondaire_a_2
    hostname: secondaire_a_2
    ports:
      - "27019:27017"
    command: ["mongod", "--replSet", "replicaSet_a", "--shardsvr", "--bind_ip_all", "--port", "27017"]
    volumes:
      - ./data/secondaire_a_2:/data/db
    networks:
      - mongoCluster
  
  secondaire_a_3:
    image: mongo:6
    container_name: secondaire_a_3
    hostname: secondaire_a_3
    ports:
      - "27020:27017"
    command: ["mongod", "--replSet", "replicaSet_a", "--shardsvr", "--bind_ip_all", "--port", "27017"]
    volumes:
      - ./data/secondaire_a_3:/data/db
    networks:
      - mongoCluster
  
  # serveur b
  principal_b:
    image: mongo:6
    container_name: principal_b
    hostname: principal_b
    ports:
      - "27021:27017"
    command: ["mongod", "--replSet", "replicaSet_b", "--shardsvr", "--bind_ip_all", "--port", "27017"]
    volumes:
      - ./data/principal_b:/data/db
    networks:
      - mongoCluster
  
  secondaire_b_1:
    image: mongo:6
    container_name: secondaire_b_1
    hostname: secondaire_b_1
    ports:
      - "27022:27017"
    command: ["mongod", "--replSet", "replicaSet_b", "--shardsvr", "--bind_ip_all", "--port", "27017"]
    volumes:
      - ./data/secondaire_b_1:/data/db
    networks:
      - mongoCluster
  
  secondaire_b_2:
    image: mongo:6
    container_name: secondaire_b_2
    hostname: secondaire_b_2
    ports:
      - "27023:27017"
    command: ["mongod", "--replSet", "replicaSet_b", "--shardsvr", "--bind_ip_all", "--port", "27017"]
    volumes:
      - ./data/secondaire_b_2:/data/db
    networks:
      - mongoCluster
  
  secondaire_b_3:
    image: mongo:6
    container_name: secondaire_b_3
    hostname: secondaire_b_3
    ports:
      - "27024:27017"
    command: ["mongod", "--replSet", "replicaSet_b", "--shardsvr", "--bind_ip_all", "--port", "27017"]
    volumes:
      - ./data/secondaire_b_3:/data/db
    networks:
      - mongoCluster

  # serveur c
  principal_c:
    image: mongo:6
    container_name: principal_c
    hostname: principal_c
    ports:
      - "27025:27017"
    command: ["mongod", "--replSet", "replicaSet_c", "--shardsvr", "--bind_ip_all", "--port", "27017"]
    volumes:
      - ./data/principal_c:/data/db
    networks:
      - mongoCluster
  
  secondaire_c_1:
    image: mongo:6
    container_name: secondaire_c_1
    hostname: secondaire_c_1
    ports:
      - "27026:27017"
    command: ["mongod", "--replSet", "replicaSet_c", "--shardsvr", "--bind_ip_all", "--port", "27017"]
    volumes:
      - ./data/secondaire_c_1:/data/db
    networks:
      - mongoCluster
  
  secondaire_c_2:
    image: mongo:6
    container_name: secondaire_c_2
    hostname: secondaire_c_2
    ports:
      - "27027:27017"
    command: ["mongod", "--replSet", "replicaSet_c", "--shardsvr", "--bind_ip_all", "--port", "27017"]
    volumes:
      - ./data/secondaire_c_2:/data/db
    networks:
      - mongoCluster
  
  secondaire_c_3:
    image: mongo:6
    container_name: secondaire_c_3
    hostname: secondaire_c_3
    ports:
      - "27028:27017"
    command: ["mongod", "--replSet", "replicaSet_c", "--shardsvr", "--bind_ip_all", "--port", "27017"]
    volumes:
      - ./data/secondaire_c_3:/data/db
    networks:
      - mongoCluster

networks:
  mongoCluster:
    driver: bridge